#!/usr/bin/env bash
# configue laod balancer

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy

config="
frontend haproxy_balancer
bind *:80
mode http
default_backend webservers

backend webservers
balance roundrobin
server 375496-web-01 100.26.10.43:80 check
server 375496-web-02 100.25.162.168:80 check
"

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo systemctl enable haproxy
sudo service haproxy restart
